-- IF NOT EXISTS to avoid spring boot create many times
CREATE TABLE IF NOT EXISTS PRODUCT
(
    PRODUCT_ID         INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME       VARCHAR(128)  NOT NULL,
    CATEGORY           VARCHAR(32)  NOT NULL,
    IMAGE_URL          VARCHAR(256) NOT NULL,
    PRICE              INT          NOT NULL,
    STOCK              INT          NOT NULL,
    DESCRIPTION        VARCHAR(1024),
    CREATE_TIME        TIMESTAMP    NOT NULL,
    LAST_MODIFIED_TIME TIMESTAMP    NOT NULL
);

 CREATE TABLE IF NOT EXISTS `USER`
(
    USER_ID            INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMAIL              VARCHAR(256) NOT NULL UNIQUE,
    `PASSWORD`         VARCHAR(256) NOT NULL,
    CREATE_TIME        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    LAST_MODIFIED_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS USER_ORDER
(
    ORDER_ID           INT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID            INT       NOT NULL,
    TOTAL_AMOUNT       INT       NOT NULL, -- 訂單總花費
    CREATE_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM
(
    ORDER_ITEM_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID      INT NOT NULL,
    PRODUCT_ID    INT NOT NULL,
    QUANTITY      INT NOT NULL, -- 商品數量
    AMOUNT        INT NOT NULL  -- 商品花費
);
